// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var Progress;
    Progress = (function() {
      Progress.prototype._cnt = 0;

      Progress.prototype._loaded = 0;

      Progress.prototype._total = 0;

      Progress.prototype._imgs = [];

      Progress.prototype._fnc = {};

      function Progress() {
        this.loaded = __bind(this.loaded, this);
      }

      Progress.prototype.load = function(imgs, fnc) {
        var img, _results;
        this._imgs = imgs;
        this._fnc = fnc;
        this._total = this._imgs.length;
        if (this._total > 0) {
          _results = [];
          while (this._cnt < this._total) {
            img = new Image();
            img.src = this._imgs[this._cnt];
            img.addEventListener('load', this.loaded, false);
            _results.push(this._cnt++);
          }
          return _results;
        } else {
          this._fnc();
          return this.start();
        }
      };

      Progress.prototype.loaded = function() {
        this._loaded++;
        if (this._loaded === this._total) {
          return this._fnc();
        }
      };

      Progress.prototype.start = function() {
        var end;
        $('body>*:not(#progress)').css('opacity', 1);
        end = function() {
          return $('#progress').remove();
        };
        return $('#progress').addClass('pageOut').bind('\
          webkitTransitionEnd\
          transitionend\
          oTransitionEnd\
          msTransitionEnd\
        ', end);
      };

      return Progress;

    })();
    return new Progress();
  });

}).call(this);
